<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework />
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" PrivateAssets="all" />
    <PackageReference Include="TUnit" PrivateAssets="all" />

    <ProjectReference Include="../../src/LoadingCache/LoadingCache.csproj" />
  </ItemGroup>
</Project>
