<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <LangVersion>14.0</LangVersion>
    <TargetFramework />
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/LoadingCache/LoadingCache.csproj" />
    <PackageReference Include="TUnit.Assertions" PrivateAssets="all" />
  </ItemGroup>
</Project>
